services:
  mysql:
    image: mariadb:11.8.3
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "40000:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -proot || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin_container
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
      MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
    ports:
      - "40001:80"
    networks:
      - app_network

  redis:
    image: redis:8.2.1
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "40002:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge
